version: '3.4'

services:
  curriculum-designer:
    hostname: curriculum_designer
    container_name: curriculum_designer
    restart: always
    build:
      context: "."
    ports:
      - 8080:6060
    networks:
      - config_qmediator


networks:
  config_qmediator:
    external: true